---
# Project Variables
dockerUser: geoffh1977
dockerUserEmail: geoffh1977@gmail.com
license: gnu-gpl-v3.0

# Source Build Variables
buildImageName: openjdk8
buildImageVersion: latest

# Final Image Variables
finalImageName: elasticsearch
finalImageVersion: 6.7.2

# Application Config
appName: Elasticsearch
elasticsearchSha512: 7e2dd65dc10d117002dca309d5fd450e218d06f8ff5ed675a219c5bfb1367afdb7f00f9a5866628e475da38c91692e9eff29140c25cf1779fb71619ff50d784c
